require:
  - rubocop-rspec
  - rubocop-gitlab-security
  - rubocop-performance
  - rubocop-rails
  - rubocop-faker

AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: false
  TargetRubyVersion: 2.7

Encoding:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'

Style/LambdaCall:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false # Add our behaviour

Layout/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#']
  Exclude:
    - 'db/migrate/*'
    - 'spec/database/*'

Layout/ArgumentAlignment:
  Enabled: false # Align the arguments of a method call if they span more than one line

Metrics/ClassLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/Delegate:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
  # Ignore migration DSL
  - db/migrate/*
  # Ignore RSpec DSL
  - spec/**/*
  # Ignore Rake task DSL
  - Rakefile

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/Open:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
Bundler/InsecureProtocolSource:
  Enabled: true
Rails/OutputSafety:
  Enabled: true

# from gitlab
# bundle exec rubocop --require rubocop-gitlab-security
GitlabSecurity/DeepMunge:
  Enabled: true
GitlabSecurity/JsonSerialization:
  Enabled: true
GitlabSecurity/RedirectToParamsUpdate:
  Enabled: true
GitlabSecurity/SendFileParams:
  Enabled: true
GitlabSecurity/SqlInjection:
  Enabled: true
GitlabSecurity/SystemCommandInjection:
  Enabled: true
